---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: 856511401021.dkr.ecr.us-east-2.amazonaws.com/ecr-eks-demo-july2025:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
    k8s-app: springboot-app
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8085
      protocol: TCP
