---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: 621402808084.dkr.ecr.us-east-2.amazonaws.com/ecr/newrepo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
    k8s-app: springboot-app
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
